version: "3"
services:
  web_erpenocis_jenkins:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "13028:3000"
      - "15028:4000"
    volumes: 
      - ./erpenocis:/opt/app
      - gem_cache_erpenocis_jenkins:/gems
    env_file: 
      - .env/jenkins/database_erpenocis
      - .env/jenkins/web_erpenocis
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_erpenocis_jenkins
    networks:
      - network_erpenocis_jenkins
    stdin_open: true
    tty: true
  webpack_dev_server_erpenocis_jenkins:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "14028:4028"
    volumes: 
      - ./erpenocis:/opt/app
      - gem_cache_erpenocis_jenkins:/gems
    env_file: 
      - .env/jenkins/database_erpenocis
      - .env/jenkins/web_erpenocis
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network_erpenocis_jenkins
  database_erpenocis_jenkins:
    image: postgres
    env_file: 
      - .env/jenkins/database_erpenocis
    volumes: 
      - db_data_erpenocis_jenkins:/var/lib/postgresql/data
    networks:
      - network_erpenocis_jenkins
  selenium_chrome_jenkins:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "15900:5900"
    networks:
      - network_erpenocis_jenkins
volumes: 
  db_data_erpenocis_jenkins:
  gem_cache_erpenocis_jenkins:
networks:
  network_erpenocis_jenkins:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"