version: "3"
services:
  web_erpenocis:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3028:3000"
    volumes: 
      - ./erpenocis:/opt/app
      - gem_cache_erpenocis:/gems
    env_file: 
      - .env/development/database_erpenocis
      - .env/development/web_erpenocis
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_erpenocis
    networks:
      - network_erpenocis
  webpack_dev_server_erpenocis:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "4028:4028"
    volumes: 
      - ./erpenocis:/opt/app
      - gem_cache_erpenocis:/gems
    env_file: 
      - .env/development/database_erpenocis
      - .env/development/web_erpenocis
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network_erpenocis
  database_erpenocis:
    image: postgres
    env_file: 
      - .env/development/database_erpenocis
    volumes: 
      - db_data_erpenocis:/var/lib/postgresql/data
    networks:
      - network_erpenocis
volumes: 
  db_data_erpenocis:
  gem_cache_erpenocis:
networks:
  network_erpenocis:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"