require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/expense_values", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExpenseValue. As you add validations to ExpenseValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExpenseValue.create! valid_attributes
      get expense_values_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expense_value = ExpenseValue.create! valid_attributes
      get expense_value_url(expense_value)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expense_value_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      expense_value = ExpenseValue.create! valid_attributes
      get edit_expense_value_url(expense_value)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExpenseValue" do
        expect {
          post expense_values_url, params: { expense_value: valid_attributes }
        }.to change(ExpenseValue, :count).by(1)
      end

      it "redirects to the created expense_value" do
        post expense_values_url, params: { expense_value: valid_attributes }
        expect(response).to redirect_to(expense_value_url(ExpenseValue.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExpenseValue" do
        expect {
          post expense_values_url, params: { expense_value: invalid_attributes }
        }.to change(ExpenseValue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post expense_values_url, params: { expense_value: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested expense_value" do
        expense_value = ExpenseValue.create! valid_attributes
        patch expense_value_url(expense_value), params: { expense_value: new_attributes }
        expense_value.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the expense_value" do
        expense_value = ExpenseValue.create! valid_attributes
        patch expense_value_url(expense_value), params: { expense_value: new_attributes }
        expense_value.reload
        expect(response).to redirect_to(expense_value_url(expense_value))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        expense_value = ExpenseValue.create! valid_attributes
        patch expense_value_url(expense_value), params: { expense_value: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expense_value" do
      expense_value = ExpenseValue.create! valid_attributes
      expect {
        delete expense_value_url(expense_value)
      }.to change(ExpenseValue, :count).by(-1)
    end

    it "redirects to the expense_values list" do
      expense_value = ExpenseValue.create! valid_attributes
      delete expense_value_url(expense_value)
      expect(response).to redirect_to(expense_values_url)
    end
  end
end
