require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/january_solds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JanuarySold. As you add validations to JanuarySold, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JanuarySold.create! valid_attributes
      get january_solds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      january_sold = JanuarySold.create! valid_attributes
      get january_sold_url(january_sold)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_january_sold_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      january_sold = JanuarySold.create! valid_attributes
      get edit_january_sold_url(january_sold)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JanuarySold" do
        expect {
          post january_solds_url, params: { january_sold: valid_attributes }
        }.to change(JanuarySold, :count).by(1)
      end

      it "redirects to the created january_sold" do
        post january_solds_url, params: { january_sold: valid_attributes }
        expect(response).to redirect_to(january_sold_url(JanuarySold.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JanuarySold" do
        expect {
          post january_solds_url, params: { january_sold: invalid_attributes }
        }.to change(JanuarySold, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post january_solds_url, params: { january_sold: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested january_sold" do
        january_sold = JanuarySold.create! valid_attributes
        patch january_sold_url(january_sold), params: { january_sold: new_attributes }
        january_sold.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the january_sold" do
        january_sold = JanuarySold.create! valid_attributes
        patch january_sold_url(january_sold), params: { january_sold: new_attributes }
        january_sold.reload
        expect(response).to redirect_to(january_sold_url(january_sold))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        january_sold = JanuarySold.create! valid_attributes
        patch january_sold_url(january_sold), params: { january_sold: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested january_sold" do
      january_sold = JanuarySold.create! valid_attributes
      expect {
        delete january_sold_url(january_sold)
      }.to change(JanuarySold, :count).by(-1)
    end

    it "redirects to the january_solds list" do
      january_sold = JanuarySold.create! valid_attributes
      delete january_sold_url(january_sold)
      expect(response).to redirect_to(january_solds_url)
    end
  end
end
