require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_situations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectSituation. As you add validations to ProjectSituation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectSituation.create! valid_attributes
      get project_situations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_situation = ProjectSituation.create! valid_attributes
      get project_situation_url(project_situation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_situation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      project_situation = ProjectSituation.create! valid_attributes
      get edit_project_situation_url(project_situation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectSituation" do
        expect {
          post project_situations_url, params: { project_situation: valid_attributes }
        }.to change(ProjectSituation, :count).by(1)
      end

      it "redirects to the created project_situation" do
        post project_situations_url, params: { project_situation: valid_attributes }
        expect(response).to redirect_to(project_situation_url(ProjectSituation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectSituation" do
        expect {
          post project_situations_url, params: { project_situation: invalid_attributes }
        }.to change(ProjectSituation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_situations_url, params: { project_situation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_situation" do
        project_situation = ProjectSituation.create! valid_attributes
        patch project_situation_url(project_situation), params: { project_situation: new_attributes }
        project_situation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_situation" do
        project_situation = ProjectSituation.create! valid_attributes
        patch project_situation_url(project_situation), params: { project_situation: new_attributes }
        project_situation.reload
        expect(response).to redirect_to(project_situation_url(project_situation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        project_situation = ProjectSituation.create! valid_attributes
        patch project_situation_url(project_situation), params: { project_situation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_situation" do
      project_situation = ProjectSituation.create! valid_attributes
      expect {
        delete project_situation_url(project_situation)
      }.to change(ProjectSituation, :count).by(-1)
    end

    it "redirects to the project_situations list" do
      project_situation = ProjectSituation.create! valid_attributes
      delete project_situation_url(project_situation)
      expect(response).to redirect_to(project_situations_url)
    end
  end
end
