require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supplier_invoices", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SupplierInvoice. As you add validations to SupplierInvoice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SupplierInvoice.create! valid_attributes
      get supplier_invoices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supplier_invoice = SupplierInvoice.create! valid_attributes
      get supplier_invoice_url(supplier_invoice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_supplier_invoice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      supplier_invoice = SupplierInvoice.create! valid_attributes
      get edit_supplier_invoice_url(supplier_invoice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SupplierInvoice" do
        expect {
          post supplier_invoices_url, params: { supplier_invoice: valid_attributes }
        }.to change(SupplierInvoice, :count).by(1)
      end

      it "redirects to the created supplier_invoice" do
        post supplier_invoices_url, params: { supplier_invoice: valid_attributes }
        expect(response).to redirect_to(supplier_invoice_url(SupplierInvoice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SupplierInvoice" do
        expect {
          post supplier_invoices_url, params: { supplier_invoice: invalid_attributes }
        }.to change(SupplierInvoice, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post supplier_invoices_url, params: { supplier_invoice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supplier_invoice" do
        supplier_invoice = SupplierInvoice.create! valid_attributes
        patch supplier_invoice_url(supplier_invoice), params: { supplier_invoice: new_attributes }
        supplier_invoice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the supplier_invoice" do
        supplier_invoice = SupplierInvoice.create! valid_attributes
        patch supplier_invoice_url(supplier_invoice), params: { supplier_invoice: new_attributes }
        supplier_invoice.reload
        expect(response).to redirect_to(supplier_invoice_url(supplier_invoice))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        supplier_invoice = SupplierInvoice.create! valid_attributes
        patch supplier_invoice_url(supplier_invoice), params: { supplier_invoice: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supplier_invoice" do
      supplier_invoice = SupplierInvoice.create! valid_attributes
      expect {
        delete supplier_invoice_url(supplier_invoice)
      }.to change(SupplierInvoice, :count).by(-1)
    end

    it "redirects to the supplier_invoices list" do
      supplier_invoice = SupplierInvoice.create! valid_attributes
      delete supplier_invoice_url(supplier_invoice)
      expect(response).to redirect_to(supplier_invoices_url)
    end
  end
end
